/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    projects: Project;
    services: Service;
    blog: Blog;
    media: Media;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    seo: Seo;
    nosotros: Nosotro;
    home: Home;
    cta: Cta;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    nosotros: NosotrosSelect<false> | NosotrosSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    cta: CtaSelect<false> | CtaSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role?: ('admin' | 'editor' | 'viewer') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  slug: string;
  category: string;
  heroImage: string | Media;
  description: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specs: {
    client: string;
    location: string;
    year: string;
    area: string;
  };
  galleryImages?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * URL del video (YouTube embed URL o video URL)
   */
  video?: string | null;
  status?: ('draft' | 'published' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  pretitulo: string;
  titulo: string;
  slug: string;
  featured_image: string | Media;
  titulo2: string;
  parrafo1: string;
  parrafo2: string;
  caracteristicas?: {
    items?:
      | {
          caracteristica: string;
          imagen: string | Media;
          id?: string | null;
        }[]
      | null;
  };
  galeria_visual?:
    | {
        imagen: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  titulo: string;
  slug: string;
  subtitulo: string;
  featured_image: string | Media;
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status?: ('draft' | 'published' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  position: string;
  company: string;
  quote: string;
  image?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  heroImage?: T;
  description?: T;
  content?: T;
  specs?:
    | T
    | {
        client?: T;
        location?: T;
        year?: T;
        area?: T;
      };
  galleryImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  video?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  pretitulo?: T;
  titulo?: T;
  slug?: T;
  featured_image?: T;
  titulo2?: T;
  parrafo1?: T;
  parrafo2?: T;
  caracteristicas?:
    | T
    | {
        items?:
          | T
          | {
              caracteristica?: T;
              imagen?: T;
              id?: T;
            };
      };
  galeria_visual?:
    | T
    | {
        imagen?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  subtitulo?: T;
  featured_image?: T;
  contenido?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  company?: T;
  quote?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  primaryColor?: string | null;
  /**
   * Logo para modo claro (login/admin header)
   */
  adminLogoLight?: (string | null) | Media;
  /**
   * Logo para modo oscuro (login/admin header)
   */
  adminLogoDark?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: string;
  meta_title: string;
  meta_description: string;
  favicon?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nosotros".
 */
export interface Nosotro {
  id: string;
  pretitulo1: string;
  titulo: string;
  subtitulo: string;
  galeria1?:
    | {
        imagen: string | Media;
        id?: string | null;
      }[]
    | null;
  titulo2: string;
  parrafo1: string;
  seccion_pilares: {
    pretitulo: string;
    titulo: string;
    pilares?:
      | {
          /**
           * Selecciona el icono Lucide para este pilar
           */
          icono:
            | 'Heart'
            | 'Star'
            | 'Shield'
            | 'Zap'
            | 'Target'
            | 'Compass'
            | 'HardHat'
            | 'Building'
            | 'FileText'
            | 'Wrench'
            | 'Settings'
            | 'Users'
            | 'Award'
            | 'TrendingUp'
            | 'Lightbulb'
            | 'Rocket'
            | 'Anchor'
            | 'PenTool'
            | 'CheckCircle'
            | 'Layers';
          titulo: string;
          parrafo: string;
          id?: string | null;
        }[]
      | null;
  };
  seccion_equipo: {
    titulo: string;
    subtitulo: string;
    personas?:
      | {
          imagen: string | Media;
          nombre: string;
          puesto: string;
          parrafo: string;
          /**
           * URLs de redes sociales (opcional)
           */
          redes_sociales?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  hero: {
    imagen?: (string | null) | Media;
    video?: string | null;
    pretitulo?: string | null;
    titulo: string;
    subtitulo?: string | null;
    parrafo?: string | null;
    texto_boton_1?: string | null;
    url_boton_1?: string | null;
    texto_boton_2?: string | null;
    url_boton_2?: string | null;
  };
  seccion2?: {
    pretitulo?: string | null;
    titulo?: string | null;
    parrafo?: string | null;
    imagen_pretitulo?: string | null;
    imagen_titulo?: string | null;
    imagen_subtitulo?: string | null;
    items?: {
      item1?: string | null;
      item2?: string | null;
      item3?: string | null;
      item4?: string | null;
    };
    imagen?: (string | null) | Media;
    texto_boton?: string | null;
    url_boton?: string | null;
  };
  servicios?: {
    pretitulo?: string | null;
    titulo?: string | null;
    subtitulo?: string | null;
  };
  soluciones?: {
    pretitulo?: string | null;
    titulo?: string | null;
    parrafo?: string | null;
  };
  trayectoria?: {
    pretitulo?: string | null;
    titulo?: string | null;
    items?:
      | {
          imagen?: (string | null) | Media;
          titulo?: string | null;
          subtitulo?: string | null;
          parrafo?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  portafolio?: {
    pretitulo?: string | null;
    titulo?: string | null;
    parrafo?: string | null;
  };
  logotipos_instituciones?:
    | {
        imagen?: (string | null) | Media;
        nombre?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta".
 */
export interface Cta {
  id: string;
  background_image?: (string | null) | Media;
  pretitulo: string;
  titulo: string;
  subtitulo: string;
  texto_boton: string;
  /**
   * URL del botón (ej: /contacto, https://..., #seccion)
   */
  enlace_boton: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  primaryColor?: T;
  adminLogoLight?: T;
  adminLogoDark?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  meta_title?: T;
  meta_description?: T;
  favicon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nosotros_select".
 */
export interface NosotrosSelect<T extends boolean = true> {
  pretitulo1?: T;
  titulo?: T;
  subtitulo?: T;
  galeria1?:
    | T
    | {
        imagen?: T;
        id?: T;
      };
  titulo2?: T;
  parrafo1?: T;
  seccion_pilares?:
    | T
    | {
        pretitulo?: T;
        titulo?: T;
        pilares?:
          | T
          | {
              icono?: T;
              titulo?: T;
              parrafo?: T;
              id?: T;
            };
      };
  seccion_equipo?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
        personas?:
          | T
          | {
              imagen?: T;
              nombre?: T;
              puesto?: T;
              parrafo?: T;
              redes_sociales?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        imagen?: T;
        video?: T;
        pretitulo?: T;
        titulo?: T;
        subtitulo?: T;
        parrafo?: T;
        texto_boton_1?: T;
        url_boton_1?: T;
        texto_boton_2?: T;
        url_boton_2?: T;
      };
  seccion2?:
    | T
    | {
        pretitulo?: T;
        titulo?: T;
        parrafo?: T;
        imagen_pretitulo?: T;
        imagen_titulo?: T;
        imagen_subtitulo?: T;
        items?:
          | T
          | {
              item1?: T;
              item2?: T;
              item3?: T;
              item4?: T;
            };
        imagen?: T;
        texto_boton?: T;
        url_boton?: T;
      };
  servicios?:
    | T
    | {
        pretitulo?: T;
        titulo?: T;
        subtitulo?: T;
      };
  soluciones?:
    | T
    | {
        pretitulo?: T;
        titulo?: T;
        parrafo?: T;
      };
  trayectoria?:
    | T
    | {
        pretitulo?: T;
        titulo?: T;
        items?:
          | T
          | {
              imagen?: T;
              titulo?: T;
              subtitulo?: T;
              parrafo?: T;
              id?: T;
            };
      };
  portafolio?:
    | T
    | {
        pretitulo?: T;
        titulo?: T;
        parrafo?: T;
      };
  logotipos_instituciones?:
    | T
    | {
        imagen?: T;
        nombre?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta_select".
 */
export interface CtaSelect<T extends boolean = true> {
  background_image?: T;
  pretitulo?: T;
  titulo?: T;
  subtitulo?: T;
  texto_boton?: T;
  enlace_boton?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}