// Shim to allow `import { importMap } from '../importMap'` from the admin catch-all page.
// The actual import map is generated by `payload generate:importmap` as `importMap.js`.
import { importMap as generatedImportMap } from './importMap.js'

export const importMap = generatedImportMap
